services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tracing:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      DATABASE_URL: ${DATABASE_URL}

